update circleci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,15 +17,15 @@ jobs:
     steps:
       - checkout
       - run:
-            environment:
-              YARN_ENABLE_IMMUTABLE_INSTALLS: false
-            command: |
-                yarn set version 3.2.2 && yarn install && yarn build && yarn workspace @1kv/common ci:checkCandidatesFile
+          environment:
+            YARN_ENABLE_IMMUTABLE_INSTALLS: false
+          command: |
+            yarn set version 3.2.2 && yarn install && yarn build && yarn workspace @1kv/common ci:checkCandidatesFile
 
   checkCoreESLint:
     docker:
       - image: node:18
-    resource_class: large      
+    resource_class: large
     steps:
       - checkout
       - run:
@@ -34,33 +34,42 @@ jobs:
           command: |
             yarn set version 3.2.2 && yarn install && yarn build && yarn workspace @1kv/core lint
 
-#  checkCommonESLint:
-#    docker:
-#      - image: node:18
-#    resource_class: large
-#    steps:
-#      - checkout
-#      - run:
-#          environment:
-#            YARN_ENABLE_IMMUTABLE_INSTALLS: false
-#          command: |
-#            yarn set version 3.2.2 && yarn install && yarn build && yarn workspace @1kv/common lint
+  #  checkCommonESLint:
+  #    docker:
+  #      - image: node:18
+  #    resource_class: large
+  #    steps:
+  #      - checkout
+  #      - run:
+  #          environment:
+  #            YARN_ENABLE_IMMUTABLE_INSTALLS: false
+  #          command: |
+  #            yarn set version 3.2.2 && yarn install && yarn build && yarn workspace @1kv/common lint
 
-
-  testCommonUnit:
-    docker:
-      - image: node:bullseye
-    resource_class: xlarge
-    steps:
-      - checkout
-      - run:
-          environment:
-            YARN_ENABLE_IMMUTABLE_INSTALLS: false
-          command: |
-            if ! yarn set version 3.2.2 && yarn install && yarn build && yarn workspace @1kv/common test:unit --testTimeout=60000; then
-              echo "Unit tests failed"
-              exit 0
-            fi
+testCommonUnit:
+  docker:
+    - image: node:bullseye
+  resource_class: xlarge
+  steps:
+    - checkout
+    - run:
+        environment:
+          YARN_ENABLE_IMMUTABLE_INSTALLS: false
+        command: |
+          yarn set version 3.2.2
+          yarn install
+          yarn build
+          if ! yarn workspace @1kv/common test:unit --testTimeout=60000; then
+            echo "Unit tests failed, but not failing the job."
+            echo 'export TESTS_FAILED=true' >> $BASH_ENV
+          fi
+    - run:
+        name: "Handle Test Failures"
+        command: |
+          if [ "${TESTS_FAILED}" == "true" ]; then
+            echo "Tests failed."
+            exit 1
+          fi
 
   testCommonInt:
     docker:
@@ -77,17 +86,17 @@ jobs:
               exit 0
             fi
 
-#  testCore:
-#    docker:
-#      - image: node:18
-#    resource_class: large
-#    steps:
-#      - checkout
-#      - run:
-#          environment:
-#            YARN_ENABLE_IMMUTABLE_INSTALLS: false
-#          command: |
-#            yarn set version 3.2.2 && yarn install && yarn build && yarn workspace @1kv/core test
+  #  testCore:
+  #    docker:
+  #      - image: node:18
+  #    resource_class: large
+  #    steps:
+  #      - checkout
+  #      - run:
+  #          environment:
+  #            YARN_ENABLE_IMMUTABLE_INSTALLS: false
+  #          command: |
+  #            yarn set version 3.2.2 && yarn install && yarn build && yarn workspace @1kv/core test
 
   helmLint:
     docker:
@@ -171,7 +180,7 @@ jobs:
       - setup_remote_docker
       - run:
           command: |
-            /scripts/publish-image.sh web3f/otv-backend staging      
+            /scripts/publish-image.sh web3f/otv-backend staging
 
   publishGatewayImage:
     docker:
@@ -229,17 +238,17 @@ workflows:
   test_and_deploy:
     jobs:
       # - checkDependencies:
-          # filters:
-            # tags:
-              # only: /.*/
+      # filters:
+      # tags:
+      # only: /.*/
       - checkCandidatesFile:
           filters:
             tags:
               ignore: /pull\/[0-9]+/
-#      - checkCommonESLint:
-#          filters:
-#            tags:
-#              only: /.*/
+      #      - checkCommonESLint:
+      #          filters:
+      #            tags:
+      #              only: /.*/
       - checkCoreESLint:
           filters:
             tags:
@@ -252,10 +261,10 @@ workflows:
           filters:
             tags:
               only: /.*/
-#      - testCore:
-#          filters:
-#            tags:
-#              only: /.*/
+      #      - testCore:
+      #          filters:
+      #            tags:
+      #              only: /.*/
       - helmLint:
           filters:
             tags:
@@ -305,7 +314,7 @@ workflows:
             branches:
               only: staging
           requires:
-            - integrationTests      
+            - integrationTests
       - publishGatewayImage:
           context: dockerhub-bot
           filters:
@@ -342,5 +351,3 @@ workflows:
               only: /v[0-9]+(\.[0-9]+)*/
           requires:
             - integrationTests
-
-
